In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt

In [2]:
random_index = np.random.choice(range(50), 5, replace = False)
random_index

array([ 7, 36, 12, 17, 18])

In [13]:
random_inputs = []
for i in random_index:
    random_inputs.append(np.eye(voc_size)[skip_grams[i][0]])

IndexError: list index out of range

In [3]:
sentences = ["apple banana fruit", "banana orange fruit", "orange banana fruit",
                 "dog cat animal", "cat monkey animal", "monkey dog animal"]

In [4]:
word_sequence = ' '.join(sentences).split()
print(word_sequence)

['apple', 'banana', 'fruit', 'banana', 'orange', 'fruit', 'orange', 'banana', 'fruit', 'dog', 'cat', 'animal', 'cat', 'monkey', 'animal', 'monkey', 'dog', 'animal']


In [5]:
word_list = ' '.join(sentences).split()
print(word_list)

['apple', 'banana', 'fruit', 'banana', 'orange', 'fruit', 'orange', 'banana', 'fruit', 'dog', 'cat', 'animal', 'cat', 'monkey', 'animal', 'monkey', 'dog', 'animal']


In [6]:
len(word_sequence)

18

In [7]:
word_sequence = " ".join(sentences).split()
word_list = " ".join(sentences).split()
word_list = list(set(word_list))
word_dict = {w: i for i, w in enumerate(word_list)}
voc_size = len(word_list)


In [20]:
print(len(word_sequence))
print(word_sequence)

18
['apple', 'banana', 'fruit', 'banana', 'orange', 'fruit', 'orange', 'banana', 'fruit', 'dog', 'cat', 'animal', 'cat', 'monkey', 'animal', 'monkey', 'dog', 'animal']


In [31]:
word_dict[word_sequence[-1]]

3

In [29]:
# skip_grams = []
# for i in range(0, len(word_sequence)-1):
#     target = word_dict[word_sequence[i]]
#     context = [word_dict[word_sequence[i - 1]], word_dict[word_sequence[i + 1]]]
#     for w in context:
#         skip_grams.append([target, w])

In [30]:
# skip_grams

[[6, 3],
 [6, 7],
 [7, 6],
 [7, 5],
 [5, 7],
 [5, 7],
 [7, 5],
 [7, 4],
 [4, 7],
 [4, 5],
 [5, 4],
 [5, 4],
 [4, 5],
 [4, 7],
 [7, 4],
 [7, 5],
 [5, 7],
 [5, 0],
 [0, 5],
 [0, 1],
 [1, 0],
 [1, 3],
 [3, 1],
 [3, 1],
 [1, 3],
 [1, 2],
 [2, 1],
 [2, 3],
 [3, 2],
 [3, 2],
 [2, 3],
 [2, 0],
 [0, 2],
 [0, 3]]

In [44]:
skip_grams = []
for i in range(1, len(word_sequence) - 1):
    target = word_dict[word_sequence[i]]
    context = [word_dict[word_sequence[i - 1]], word_dict[word_sequence[i + 1]]]
    for w in context:
        skip_grams.append([target, w])

In [45]:
word_dict

{'dog': 0,
 'cat': 1,
 'monkey': 2,
 'animal': 3,
 'orange': 4,
 'fruit': 5,
 'apple': 6,
 'banana': 7}

In [88]:
skip_grams

[[7, 6],
 [7, 5],
 [5, 7],
 [5, 7],
 [7, 5],
 [7, 4],
 [4, 7],
 [4, 5],
 [5, 4],
 [5, 4],
 [4, 5],
 [4, 7],
 [7, 4],
 [7, 5],
 [5, 7],
 [5, 0],
 [0, 5],
 [0, 1],
 [1, 0],
 [1, 3],
 [3, 1],
 [3, 1],
 [1, 3],
 [1, 2],
 [2, 1],
 [2, 3],
 [3, 2],
 [3, 2],
 [2, 3],
 [2, 0],
 [0, 2],
 [0, 3]]

In [47]:
print(len(skip_grams))

32


In [61]:
skip_grams[20]

[3, 1]

In [48]:
batch_size = 2

random_index = np.random.choice(range(len(skip_grams)), batch_size, replace = False)
random_index

array([13, 20])

In [55]:
random_inputs = []
random_labels = []

for i in random_index:
    random_inputs.append(np.eye(voc_size)[skip_grams[i][0]])
    random_labels.append(skip_grams[i][1])

In [56]:
print(random_inputs)
print(random_labels)

[array([0., 0., 0., 0., 0., 0., 0., 1.]), array([0., 0., 0., 1., 0., 0., 0., 0.])]
[5, 1]


In [62]:
input_batch = torch.Tensor(random_inputs)
input_batch

tensor([[0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0., 0.]])

In [65]:
target_batch = torch.LongTensor(random_labels)
target_batch

tensor([5, 1])

In [67]:
embedding_size = 2

w = nn.Linear(voc_size, embedding_size, bias = False)
W = w(input_batch)
W

tensor([[-0.3348, -0.0765],
        [ 0.0415, -0.2063]], grad_fn=<MmBackward>)

In [78]:
list(w.parameters())
# y=ax에 대한 a에 대한 벡터가 밑의 값이고 x는 input_batch에 있는 벡터이다


[Parameter containing:
 tensor([[ 0.1549,  0.1987, -0.0752,  0.0415, -0.0648,  0.0887, -0.0544, -0.3348],
         [ 0.1187,  0.0560,  0.1742, -0.2063, -0.1999, -0.3254,  0.2055, -0.0765]],
        requires_grad=True)]

In [70]:
WT = nn.Linear(embedding_size, voc_size, bias = False)
out = WT(W)
out

tensor([[ 0.2562,  0.1322,  0.1841, -0.0146, -0.1683,  0.1850, -0.0414,  0.1326],
        [ 0.1015, -0.1590,  0.0045,  0.0285,  0.0682,  0.0955, -0.1416, -0.0656]],
       grad_fn=<MmBackward>)

In [71]:
target_batch

tensor([5, 1])

In [73]:
criterion = nn.CrossEntropyLoss()
loss = criterion(out, target_batch)
print(loss)

tensor(2.1104, grad_fn=<NllLossBackward>)


In [74]:
word_list

['dog', 'cat', 'monkey', 'animal', 'orange', 'fruit', 'apple', 'banana']

In [85]:
for i, label in enumerate(word_list):
    print(i, label)

0 dog
1 cat
2 monkey
3 animal
4 orange
5 fruit
6 apple
7 banana
