In [27]:
s = 'i like coffee'

w = s.split()

print(w)

['i', 'like', 'coffee']


In [28]:
w[-1]

'coffee'

In [29]:
 word_dict = {w: i for i, w in enumerate(w)}

In [30]:
word_dict

{'i': 0, 'like': 1, 'coffee': 2}

In [36]:
len(word_dict)

3

In [31]:
i = [word_dict[n] for n in w[:-1]]

In [32]:
i

[0, 1]

In [33]:
import torch 

print(torch.ones(128))
d = torch.ones(128)
len(d)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])


128

In [34]:
X = torch.tensor([[[1,1,1],[2,2,3],[3,5,7]]])
X

tensor([[[1, 1, 1],
         [2, 2, 3],
         [3, 5, 7]]])

In [35]:
X = X.view(-1)
X

tensor([1, 1, 1, 2, 2, 3, 3, 5, 7])

In [ ]:
torch.LongTensor()

In [39]:
sentences = ['i like cat', 'i love coffee', 'i hate sushi']
word_list = ' '.join(sentences).split()
# ,구분자를 추가하여 한칸 띄어서 각 단어를 문장에서 분리

word_list = list(set(word_list))
# 중복 단어 제거

word_dict = {w: i for i, w in enumerate(word_list)}
# key : value 형태로 위에서 자른 단어를 넣어줌

number_dict = {i: w for i, w in enumerate(word_list)}

n_class = len(word_dict)

In [41]:
print(word_list)
print(word_dict)
print(n_class)

['like', 'cat', 'hate', 'coffee', 'sushi', 'love', 'i']
{'like': 0, 'cat': 1, 'hate': 2, 'coffee': 3, 'sushi': 4, 'love': 5, 'i': 6}
7


In [42]:
input_batch = []
target_batch = []

for sen in sentences:
    word = sen.split()
    # 문장을 단어단위로 쪼깸
    input = [word_dict[n] for n in word[:-1]]
    # word의 마지막 단어를 제외한 단어들을 dict로 넣어주고 해당 단어의 인덱스를 input변수에 넣어줌

    target = word_dict[word[-1]]
    # 마지막 단어에 대한 인덱스 값을 target변수에 저장

    input_batch.append(input)
    target_batch.append(target)

In [47]:
input_batch

[[6, 0], [6, 5], [6, 2]]

In [44]:
target_batch

[1, 3, 4]

In [49]:
word_dict

{'like': 0, 'cat': 1, 'hate': 2, 'coffee': 3, 'sushi': 4, 'love': 5, 'i': 6}

In [48]:
for sen in sentences:
    word = sen.split()
    # 문장을 단어단위로 쪼깸
    input = [word_dict[n] for n in word[:-1]]
    print(input)

[6, 0]
[6, 5]
[6, 2]


In [7]:
sentences = ['i like cat', 'i love coffee', 'i hate sushi']
word_list = ' '.join(sentences).split()
word_list = list(set(word_list))
word_dict = {w:i for i, w in enumerate(word_list)}
n_class = len(word_dict)


In [10]:
word_dict

{'sushi': 0, 'i': 1, 'coffee': 2, 'cat': 3, 'hate': 4, 'love': 5, 'like': 6}

In [8]:
input_batch = []
target_batch = []

for sen in sentences:
    word = sen.split()
    # 문장을 단어단위로 쪼깸
    input = [word_dict[n] for n in word[:-1]]
    # word의 마지막 단어를 제외한 단어들을 dict로 넣어주고 해당 단어의 인덱스를 input변수에 넣어줌

    target = word_dict[word[-1]]
    # 마지막 단어에 대한 인덱스 값을 target변수에 저장

    input_batch.append(input)
    target_batch.append(target)

In [9]:
input_batch

[[1, 6], [1, 5], [1, 4]]

In [11]:
target_batch

[3, 2, 0]

In [18]:
import torch
import torch.nn as nn
c = nn.Embedding(7,2)

input_batch = torch.LongTensor(input_batch)
print(input_batch)
c = c(input_batch)
print(c)
# 인덱스를 정해진 차원으로 설명할 수 있도록 표현 

tensor([[1, 6],
        [1, 5],
        [1, 4]])
tensor([[[-0.6542,  0.6534],
         [-0.3490, -0.6074]],

        [[-0.6542,  0.6534],
         [ 2.3379,  0.0756]],

        [[-0.6542,  0.6534],
         [-1.5639,  0.2229]]], grad_fn=<EmbeddingBackward>)


In [21]:
c.shape

torch.Size([3, 2, 2])

In [25]:
x = c.view(-1, 4)
print(x.shape)
# 각 단어를 표시하는 벡터로만 구성되어 있기 때문에 이것을 한문장을 표현할 수 있는 벡터로 표현하기 위해 view 사용 

torch.Size([3, 4])


In [28]:
h = nn.Linear(2*2, 5, bias = False)
d = nn.Parameter(torch.ones(5))


In [30]:
d

Parameter containing:
tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [32]:
tanh = torch.tanh(h(x)+d)
tanh

tensor([[ 0.7974,  0.8805,  0.6430,  0.8857,  0.9356],
        [ 0.5707,  0.9507,  0.9367, -0.0545,  0.9792],
        [ 0.7735,  0.6917,  0.6602,  0.9282,  0.7221]], grad_fn=<TanhBackward>)

In [33]:
U = nn.Linear(5, 7, bias = False)

W = nn.Linear(4, 7, bias = False)

b = nn.Parameter(torch.ones(n_class))

In [35]:
out = b + W(x) + U(tanh)
print(out)

tensor([[ 0.7374,  0.2227,  1.1237,  0.8631,  1.4766,  2.1624,  1.7502],
        [-0.1803,  1.4261,  0.7368,  1.1235,  1.2237,  0.8306,  0.6671],
        [ 1.1544, -0.1866,  0.9288,  1.3369,  1.3639,  2.2575,  1.5747]],
       grad_fn=<AddBackward0>)


In [36]:
word_dict

{'sushi': 0, 'i': 1, 'coffee': 2, 'cat': 3, 'hate': 4, 'love': 5, 'like': 6}

In [38]:
target_batch

[3, 2, 0]