In [27]:
s = 'i like coffee'

w = s.split()

print(w)

['i', 'like', 'coffee']


In [28]:
w[-1]

'coffee'

In [29]:
 word_dict = {w: i for i, w in enumerate(w)}

In [30]:
word_dict

{'i': 0, 'like': 1, 'coffee': 2}

In [36]:
len(word_dict)

3

In [31]:
i = [word_dict[n] for n in w[:-1]]

In [32]:
i

[0, 1]

In [33]:
import torch 

print(torch.ones(128))
d = torch.ones(128)
len(d)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])


128

In [34]:
X = torch.tensor([[[1,1,1],[2,2,3],[3,5,7]]])
X

tensor([[[1, 1, 1],
         [2, 2, 3],
         [3, 5, 7]]])

In [35]:
X = X.view(-1)
X

tensor([1, 1, 1, 2, 2, 3, 3, 5, 7])

In [ ]:
torch.LongTensor()

In [39]:
sentences = ['i like cat', 'i love coffee', 'i hate sushi']
word_list = ' '.join(sentences).split()
# ,구분자를 추가하여 한칸 띄어서 각 단어를 문장에서 분리

word_list = list(set(word_list))
# 중복 단어 제거

word_dict = {w: i for i, w in enumerate(word_list)}
# key : value 형태로 위에서 자른 단어를 넣어줌

number_dict = {i: w for i, w in enumerate(word_list)}

n_class = len(word_dict)

In [41]:
print(word_list)
print(word_dict)
print(n_class)

['like', 'cat', 'hate', 'coffee', 'sushi', 'love', 'i']
{'like': 0, 'cat': 1, 'hate': 2, 'coffee': 3, 'sushi': 4, 'love': 5, 'i': 6}
7


In [42]:
input_batch = []
target_batch = []

for sen in sentences:
    word = sen.split()
    # 문장을 단어단위로 쪼깸
    input = [word_dict[n] for n in word[:-1]]
    # word의 마지막 단어를 제외한 단어들을 dict로 넣어주고 해당 단어의 인덱스를 input변수에 넣어줌

    target = word_dict[word[-1]]
    # 마지막 단어에 대한 인덱스 값을 target변수에 저장

    input_batch.append(input)
    target_batch.append(target)

In [47]:
input_batch

[[6, 0], [6, 5], [6, 2]]

In [44]:
target_batch

[1, 3, 4]

In [49]:
word_dict

{'like': 0, 'cat': 1, 'hate': 2, 'coffee': 3, 'sushi': 4, 'love': 5, 'i': 6}

In [48]:
for sen in sentences:
    word = sen.split()
    # 문장을 단어단위로 쪼깸
    input = [word_dict[n] for n in word[:-1]]
    print(input)

[6, 0]
[6, 5]
[6, 2]


In [51]:

import torch.nn as nn
nn.Embedding(5,3)

Embedding(5, 3)